# Generated by Django 3.0.7 on 2020-07-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Projects',
        ),
    ]
