# Generated by Django 3.0.7 on 2020-07-07 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employee_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
