# Generated by Django 3.0.7 on 2020-07-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0016_delete_engagement'),
        ('employee', '0006_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
