# Generated by Django 3.0.7 on 2020-07-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0007_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('staffId', models.IntegerField()),
                ('level', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
            ],
        ),
    ]
