# Generated by Django 3.0.7 on 2020-06-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='staffId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
