# Generated by Django 3.0.7 on 2020-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_auto_20200623_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='progress',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
