# Generated by Django 3.0.7 on 2020-06-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_engagement_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='staffId',
        ),
        migrations.AddField(
            model_name='engagement',
            name='staff',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=models.CharField(blank=True, default='just started', max_length=30, null=True),
        ),
    ]
