# Generated by Django 3.0.7 on 2020-07-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_auto_20200701_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='staff',
        ),
        migrations.AddField(
            model_name='engagement',
            name='staff',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
