# Generated by Django 3.0.7 on 2020-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0006_auto_20200701_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('staff_id', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='staff',
        ),
        migrations.AddField(
            model_name='engagement',
            name='staff',
            field=models.ManyToManyField(to='engagement.Staff'),
        ),
    ]
