# Generated by Django 3.0.7 on 2020-07-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0008_auto_20200706_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engagement',
        ),
    ]
