# Generated by Django 3.0.7 on 2020-07-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_projects'),
        ('engagement', '0012_auto_20200706_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='staff',
            field=models.ManyToManyField(to='employee.Employee'),
        ),
    ]
