# Generated by Django 3.0.7 on 2020-07-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0013_auto_20200707_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
