# Generated by Django 3.0.7 on 2020-07-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0014_delete_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=models.CharField(blank=True, default='Proposed', max_length=30, null=True),
        ),
    ]
