# Generated by Django 3.0.7 on 2020-07-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0015_auto_20200709_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engagement',
        ),
    ]
