# Generated by Django 3.0.7 on 2020-07-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_employee'),
        ('engagement', '0016_delete_engagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Proposed', max_length=30, null=True)),
                ('progress', models.IntegerField(blank=True, default='0', null=True)),
                ('staff', models.ManyToManyField(to='employee.Employee')),
            ],
        ),
    ]
